name: frontend
description: Carbon Accounting Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.64.0
  intl: ^0.18.1
  
  # Keep your existing file_picker version for now
  file_picker: ^6.1.1
  
  # Excel/CSV processing
  excel: ^4.0.2
  csv: ^5.0.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true